disabling release from dev to prod

diff --git a/.github/workflows/prod.yml b/.github/workflows/prod.yml
--- a/.github/workflows/prod.yml
+++ b/.github/workflows/prod.yml
@@ -13,6 +13,10 @@ jobs:
 
       - name: Echo Deploy Environment Info
         run: |
+          if [[ ! ${{ github.event.inputs.tag }} =~ ^prod- ]]; then
+            echo "Invalid tag name. Tag name must start with 'prod-'"
+            exit 1
+          fi
           echo "Deploying to Prod environment..."
           echo "Using sha: ${{ github.sha }}"
       
diff --git a/.github/workflows/qa.yml b/.github/workflows/qa.yml
--- a/.github/workflows/qa.yml
+++ b/.github/workflows/qa.yml
@@ -17,6 +17,10 @@ jobs:
 
       - name: Echo Deploy Environment Info
         run: |
+          if [[ ! ${{ github.event.inputs.tag }} =~ ^qa- ]]; then
+            echo "Invalid tag name. Tag name must start with 'qa-'"
+            exit 1
+          fi
           echo "Deploying to QA environment..."
           echo "Using sha: ${{ github.sha }}"
 
